### ISSUE TITLE
lib fails on connect

### ISSUE THREAD

**Issue by tjgillies** [nu7hatch/gmail#26]
So im trying to make a test for my gmail method. this is the error:

```
Failures:

  1) sendmail method should send an email given a keywords, seeds, and a run_number, 
     Failure/Error: sendmail("hello","there",15)
     NoMethodError:
       undefined method `upcase' on nil:NilClass.
# kernel/delta/kernel.rb:79:in `upcase (method_missing)'
     # /Users/tyler/.rvm/rubies/rbx-head/lib/net/imap.rb:2496:in `text_response'
     # /Users/tyler/.rvm/rubies/rbx-head/lib/net/imap.rb:1994:in `response_untagged'
     # /Users/tyler/.rvm/rubies/rbx-head/lib/net/imap.rb:1950:in `response'
     # /Users/tyler/.rvm/rubies/rbx-head/lib/net/imap.rb:1876:in `parse'
     # /Users/tyler/.rvm/rubies/rbx-head/lib/net/imap.rb:1008:in `get_response'
     # /Users/tyler/.rvm/rubies/rbx-head/lib/net/imap.rb:917:in `initialize'
     # ./lib/mailer.rb:3:in `sendmail'
     # ./spec/mailer_spec.rb:4:in `__script__'
     # kernel/common/eval.rb:120:in `instance_eval'
     # kernel/bootstrap/array.rb:97:in `map'
     # kernel/bootstrap/array.rb:97:in `map'

```

here is my method
variables in all caps are strings switched out to protect the innocent ;)

```
def sendmail(keywords,seeds,run_number)
  gmail = Gmail.connect(USERNAME,PASSWORD)

  gmail.deliver do
    to EMAIL_ADDRESS
    subject "new machine run #{run_number}"
    body "machine run is done: keywords: #{keywords} seeds: #{seeds} URL/#{run_number}"
  end
end
```
